apiVersion: v1
kind: List
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: argo-events
      labels:
        type: infrastructure
    spec:
      project: default
      source:
        repoURL: https://github.com/novoselskiy/argo-combined-demo-1.git
        path: infrastructure/argo-events
      destination: &dest
        server: "https://kubernetes.default.svc"
        namespace: demo
      syncPolicy: &policy
        automated:
          prune: true
          selfHeal: true

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: argo-rollouts
      labels:
        type: infrastructure
    spec:
      project: default
      source:
        repoURL: https://github.com/novoselskiy/argo-combined-demo-1.git
        path: infrastructure/argo-rollouts
      destination: *dest
      syncPolicy: *policy

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: argo-workflows
      labels:
        type: infrastructure
    spec:
      project: default
      source:
        repoURL: https://github.com/novoselskiy/argo-combined-demo-1.git
        path: infrastructure/argo-workflow
      destination: *dest
      syncPolicy: *policy

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: minio
      labels:
        type: infrastructure
    spec:
      project: default
      source:
        repoURL: https://github.com/novoselskiy/argo-combined-demo-1.git
        path: infrastructure/minio
      destination: *dest
      syncPolicy: *policy

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: web-service
      labels:
        type: application
    spec:
      project: default
      source:
        repoURL: https://github.com/novoselskiy/argo-combined-demo-1.git
        path: web-service
      destination: *dest
      syncPolicy: *policy

  - apiVersion: v1
    kind: Namespace
    metadata:
      name: demo
