apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: minio
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: minio
      eventName: example
  triggers:
    - template:
        name: minio-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: arguments-parameters-
              spec:
                entrypoint: main

                arguments:
                  parameters:
                  - name: path
                    value: input.jpg

                templates:
                - name: main
                  steps:
                  - - name: find-faces
                      template: find-faces
                      arguments:
                        parameters:
                        - name: path
                          value: "{{workflow.parameters.path}}"

                  - - name: upload-result
                      template: upload-result
                      arguments:
                        artifacts:
                        - name: file
                          from: "{{steps.find-faces.outputs.artifacts.photo}}"
                      

                - name: find-faces
                  inputs:
                    parameters:
                    - name: path
                    artifacts:
                    - name: photo
                      path: /photo.jpg
                      s3:
                        endpoint: demo-minio:9000
                        insecure: true
                        bucket: demo
                        key: "{{inputs.parameters.path}}"
                        accessKeySecret:
                          name: demo-minio
                          key: accesskey
                        secretKeySecret:
                          name: demo-minio
                          key: secretkey
                  container:
                    image: vnovoselskiy/facedetect
                    command: [python]
                    args: ["/app/facedetect", "-o", "/result.jpg", "photo.jpg"]
                  outputs:
                    artifacts:
                    - name: photo
                      path: "/result.jpg"

                - name: upload-result
                  inputs:
                    artifacts:
                    - name: file
                      path: /tmp/file
                  container:
                    env:
                    - name: AWS_ACCESS_KEY_ID
                      valueFrom:
                        secretKeyRef:
                          name: demo-minio
                          key: accesskey
                    - name: AWS_SECRET_ACCESS_KEY
                      valueFrom:
                        secretKeyRef:
                          name: demo-minio
                          key: secretkey
                    image: amazon/aws-cli
                    command: [aws]
                    args: ["--endpoint-url", "http://demo-minio:9000/", "s3", "cp", "/tmp/file", "s3://demo/{{workflow.parameters.path}}.png"]
          # The container args from the workflow are overridden by the s3 notification key
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: notification.0.s3.object.key
              dest: spec.arguments.parameters.0.value
